---

name: generate a cowsay

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: output pipeline
        id: cowsay_output_id # You want id
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: 'Hello, World'
          cow: 'gopher' # ascii art list: https://github.com/Code-Hex/Neo-cowsay/tree/master/cows
          cowsay_to_output: 'cowsay'
      - name: print output
        run: |
          echo "${{ steps.cowsay_output_id.outputs.cowsay }}"    

  deploy:
    runs-on: self-hosted
    steps:
#      - name: install and run cowsay
#        run: |
#          apt update
#          apt install cowsay
#          cowsay "Test" > /var/www/html/cowsay.txt
